### Converting Original Dataset 

In [14]:
import os
import numpy as np
import h5py
from scipy.io import loadmat, savemat
from enum import Enum
from math import floor
from scipy.stats import zscore

In [15]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
def decode_utf16_array(array):
    """Decode MATLAB UTF-16 encoded uint16 arrays to strings."""
    array = array.flatten() if array.ndim == 2 else array
    return ''.join(chr(c) for c in array if c != 0)


def handle_cell_string_dataset(dataset, file_handle):
    """Handle MATLAB-style cell array of strings stored as references."""
    result = []
    for i in range(dataset.shape[0]):
        ref = dataset[i, 0]
        deref = file_handle[ref]
        value = deref[()]
        if isinstance(value, bytes):
            result.append(value.decode('utf-8'))
        elif isinstance(value, np.ndarray) and value.dtype == np.uint16:
            result.append(decode_utf16_array(value))
        else:
            result.append(value)
    return result

def iterate_group(data: h5py.Group, final_data: dict):
    """
    Recursively iterate through a h5py Group and print its structure.
    """
    for key in data.keys():
        item = data[key]
        if isinstance(item, h5py.Group):
            final_data[key] = {}
            iterate_group(item, final_data[key])
        else:
            final_data[key] = item[:]
    return final_data

def load_data_matfile(path: str, name: list[str]=None):
    data = None
    with h5py.File(path, 'r') as f:
        # List all groups in the file
        # print("Keys in the file:", list(f.keys()))
        # Access the dataset

        if len(name)==0:
            data = {}
            iterate_group(f, data)
            return data
        else:
            result = {}
            for key in name:
                if isinstance(f[key], h5py.Group):
                    # print("key is a group, iterating through it")
                    result[key] = iterate_group(f[key], {})
                elif key == 'FILE_ID':
                    result[key] = handle_cell_string_dataset(f[key], f)
                else:
                    # print("key is a dataset, returning data")
                    data = f[key][:]
                    data = data.T  # Transpose to match MATLAB's column-major order
                    result[key] = data 
            return result
        
def load_result_matfile(path: str):
    data = loadmat(path)
    return data


In [17]:
class SourceDataKeys(Enum):
    """
    Enum to represent different keys in the original mat file.
    """
    FILE_ID = 'FILE_ID'
    ANALYSIS_ID = 'analysis_ID'
    ANALYSIS_SCORE = 'analysis_SCORE'
    SFNC = 'sFNC'

### Downsampling

In [18]:
def convert_fnc_to_features(fnc_path: str, dest_path: str, name: str):
    file_path = os.path.join(fnc_path, f'{name}.mat')
    original_data = load_data_matfile(
        file_path,
        name=[
            SourceDataKeys.SFNC.value,
            SourceDataKeys.FILE_ID.value,
            SourceDataKeys.ANALYSIS_SCORE.value,
        ],
    )

    # --- find diagnosis column (case-insensitive) ---
    file_ids = original_data[SourceDataKeys.FILE_ID.value]
    label_index = next(
        (i for i, col in enumerate(file_ids) if "diagnosis" in col.lower()),
        None
    )
    if label_index is None:
        raise ValueError(f'No "diagnosis" column found in FILE_ID for {name}')

    labels = original_data[SourceDataKeys.ANALYSIS_SCORE.value][:, label_index]
    # Optional: match MATLAB’s strict check
    # uniq = np.unique(labels)
    # if not np.all(np.isin(uniq, [1, 2])):
    #     raise ValueError(f"Unexpected diagnosis codes: {uniq.tolist()}")
    labels = labels.reshape(-1, 1)

    fnc_matrices = original_data[SourceDataKeys.SFNC.value]  # shape: (N, P, P)
    N, P, _ = fnc_matrices.shape

    # --- build the lower-triangle mask excluding diagonal (k=-1) ---
    mask = np.tril(np.ones((P, P), dtype=bool), k=-1)  # P x P

    # --- replicate MATLAB's column-major flattening ---
    # 1) reshape each P×P to length P*P along Fortran (column-major) order
    # 2) take the linear indices where mask is True, also in Fortran order
    linear_idx = np.where(mask.ravel(order='F'))[0]           # size: P*(P-1)/2
    fnc_flat_F = fnc_matrices.reshape(N, P * P, order='F')    # N x (P*P)

    source_data = fnc_flat_F[:, linear_idx]                   # N x (P*(P-1)/2)
    # keep dtype default (float64) to match MATLAB; or cast if you prefer
    # source_data = source_data.astype(np.float64, copy=False)

    # append labels as the last column
    out = np.hstack([source_data, labels])

    # save with variable name = dataset name (like MATLAB)
    out_path = os.path.join(dest_path, f'{name}.mat')
    savemat(out_path, {name: out}, do_compression=True)


for i in ["FBIRN", "COBRE"]:
    fnc_dataset = convert_fnc_to_features("../original_dataset", "dataset", i)

In [19]:
### PARAMETERS
SamplingThs = 0.7
iter = 101
ntree = 201
NI_threshold = 2
TypThs = 0.8

In [20]:
import complete_random_forest.crf as crf

### Running CRF

In [ ]:
from scipy.io import savemat


def perform_crf(
    dataset_path: str,
    result_path: str,
    name: str
):
    """
    consisting of subjects with there features as columns
    last column is label of the subject
    """

    file_path = os.path.join(dataset_path, f'{name}.mat')
    dataset = load_result_matfile(file_path)[name]

    subject_count, features_count = dataset.shape

    labels = dataset[:, -1]
    label_classes = np.unique(labels)
    len_label_classes = len(label_classes)
    # class is either 1 (SZ) or 2 (HC)
    original_cls_label_indexes = dict()
    sampling_cls_label_count = [None] * len_label_classes

    for i in range(len_label_classes):
        original_cls_label_indexes[label_classes[i]] = np.where(
            labels == label_classes[i]
        )[0]
        sampling_cls_label_count[i] = floor(
            len(original_cls_label_indexes[label_classes[i]]) * SamplingThs
        )

    dtype = np.dtype([
        ("subject_id", np.int64),   # col 0
        ("count", np.int64),        # col 1
        ("non_noise_count", np.int64),      # col 2
        ("ratio", np.float64)       # col 3
    ])

    sub_noise_per_iter = np.zeros(subject_count, dtype=dtype)
    sub_noise_per_iter["subject_id"] = np.arange(1, subject_count + 1, dtype=int) # id's of all subjects
    mean_sub_sampling_length = int(np.mean(sampling_cls_label_count))

    non_noise_sampling_subjects = [] # for each sampling, subjects Ids which are not noise
    nltc_decisions = []
    for i in range(iter):
        print(f"Constructing No. {i+1} CRF for {name} dataset")
        index_temp = []
        for cls in label_classes:
            random_sampling_indexes = np.random.permutation(
                original_cls_label_indexes[cls]
            )[:mean_sub_sampling_length]
            index_temp.extend(random_sampling_indexes)

        random_indices = np.array(index_temp).astype(int)

        sub_noise_per_iter['count'][random_indices] += 1
        sampled_dataset = dataset[random_indices, :]
        attributes = zscore(sampled_dataset[:, 0:features_count-1], axis=0, ddof=1)
        sampled_dataset_labels = sampled_dataset[:, -1].reshape(-1,1)

        training_data = np.hstack((sampled_dataset_labels, attributes))

        # denoise_data, non_noise_ID, NLTC_labels =  running_crf(training_data, ntree, NI_threshold)
        instance = crf.CRF(ntree, NI_threshold)
        non_noise_ids, nltc_labels = instance.crf_v1(training_data, ntree)
        nltc_decisions.append(nltc_labels)
        # print("picked sampling number: ", sampling_indexes[non_noise_ids, i])
        non_noise_sampling_subjects.append(random_indices[non_noise_ids])

    denoise_check = np.zeros((subject_count,), dtype=int)
    for i in range(iter):
        idxs = non_noise_sampling_subjects[i]
        denoise_check [idxs] += 1

    # print("denoise count for each subject: ", denoise_check)
    sub_noise_per_iter['non_noise_count'] = denoise_check

    np.divide(sub_noise_per_iter['non_noise_count'], sub_noise_per_iter['count'], out=sub_noise_per_iter['ratio'], where=sub_noise_per_iter['count'] != 0)
    sub_noise_per_iter['ratio'] = np.round(sub_noise_per_iter['ratio'], 1)

    final_mat = np.column_stack((sub_noise_per_iter["subject_id"], sub_noise_per_iter["count"], sub_noise_per_iter["non_noise_count"], sub_noise_per_iter['ratio']))
    # print("iteration matrix: ", final_mat)

    output_path = os.path.join(result_path, f'{name}_CRF.mat')
    savemat(output_path, {
        'count': final_mat,
        'nltc_labels': nltc_decisions,
        'non_noise_ind': non_noise_sampling_subjects
    }, do_compression=True)


for name in ["FBIRN", 'COBRE']:
    perform_crf('dataset', 'results', name)

Constructing No. 1 CRF for FBIRN dataset
Constructing No. 2 CRF for FBIRN dataset
Constructing No. 3 CRF for FBIRN dataset
Constructing No. 4 CRF for FBIRN dataset
Constructing No. 5 CRF for FBIRN dataset
Constructing No. 6 CRF for FBIRN dataset
Constructing No. 7 CRF for FBIRN dataset
Constructing No. 8 CRF for FBIRN dataset
Constructing No. 9 CRF for FBIRN dataset
Constructing No. 10 CRF for FBIRN dataset
Constructing No. 11 CRF for FBIRN dataset
Constructing No. 12 CRF for FBIRN dataset
Constructing No. 13 CRF for FBIRN dataset
Constructing No. 14 CRF for FBIRN dataset
Constructing No. 15 CRF for FBIRN dataset
Constructing No. 16 CRF for FBIRN dataset
Constructing No. 17 CRF for FBIRN dataset
Constructing No. 18 CRF for FBIRN dataset
Constructing No. 19 CRF for FBIRN dataset
Constructing No. 20 CRF for FBIRN dataset
Constructing No. 21 CRF for FBIRN dataset
Constructing No. 22 CRF for FBIRN dataset
Constructing No. 23 CRF for FBIRN dataset
Constructing No. 24 CRF for FBIRN dataset
C

In [22]:
def pretty_print(mat):
    """Print with ints for first 3 cols, 1 decimal for last."""
    ids     = mat[:, 0].astype(np.int64)
    count   = mat[:, 1].astype(np.int64)
    success = mat[:, 2].astype(np.int64)
    ratio   = mat[:, 3]
    rows = [f"[{i:>3d} {c:>3d} {s:>3d} {r:>3.1f}]" for i,c,s,r in zip(ids, count, success, ratio)]
    print("\n".join(rows))

for name in ["FBIRN", "COBRE"]:
    crf = load_result_matfile('results/COBRE_CRF.mat')['count']
    pretty_print(crf)

[  1  79  78 1.0]
[  2  83  83 1.0]
[  3  80  74 0.9]
[  4  58  58 1.0]
[  5  60  60 1.0]
[  6  78  76 1.0]
[  7  64  64 1.0]
[  8  55  55 1.0]
[  9  86  86 1.0]
[ 10  69  69 1.0]
[ 11  82  82 1.0]
[ 12  51  50 1.0]
[ 13  81   5 0.1]
[ 14  61  52 0.9]
[ 15  69  69 1.0]
[ 16  60   4 0.1]
[ 17  83   0 0.0]
[ 18  80  75 0.9]
[ 19  69  12 0.2]
[ 20  60  60 1.0]
[ 21  58  58 1.0]
[ 22  54  50 0.9]
[ 23  60  10 0.2]
[ 24  85   1 0.0]
[ 25  61  61 1.0]
[ 26  66  66 1.0]
[ 27  92  92 1.0]
[ 28  82  77 0.9]
[ 29  85  85 1.0]
[ 30  65  31 0.5]
[ 31  83  83 1.0]
[ 32  77   7 0.1]
[ 33  49   4 0.1]
[ 34  81  80 1.0]
[ 35  68  68 1.0]
[ 36  55  54 1.0]
[ 37  65  65 1.0]
[ 38  63   9 0.1]
[ 39  64  64 1.0]
[ 40  74  74 1.0]
[ 41  70  70 1.0]
[ 42  77   6 0.1]
[ 43  48  48 1.0]
[ 44  64   0 0.0]
[ 45  82  77 0.9]
[ 46  63  63 1.0]
[ 47  66  66 1.0]
[ 48  74  19 0.3]
[ 49  63   0 0.0]
[ 50  70  70 1.0]
[ 51  81  59 0.7]
[ 52  62  62 1.0]
[ 53  78  77 1.0]
[ 54  73   2 0.0]
[ 55  81  80 1.0]
[ 56  78  

In [23]:
def find_typical_subjects(input_path: str, data_path: str, name: str, typical_threshold: float) -> None:

    input_file = os.path.join(input_path, f'{name}_CRF.mat')
    crf_count = load_result_matfile(input_file)['count']
    crf_count[:, 3] = np.round(crf_count[:, 3], 1)

    data_file = os.path.join(data_path, f'{name}.mat')
    data = load_result_matfile(data_file)[name]

    original_labels = data[:, -1]
    
    mask_sz = (crf_count[:,3] >= typical_threshold) & (original_labels == 1)
    mask_hc = (crf_count[:,3] >= typical_threshold) & (original_labels == 2)

    typical_group_sz = np.where(mask_sz)[0]
    typical_group_hc = np.where(mask_hc)[0]

    savemat(f'results/{name}_Typ.mat', {
        'typical_sz': typical_group_sz,
        'typical_hc': typical_group_hc,
    }, do_compression=True)

for name in ["FBIRN", "COBRE"]:
    find_typical_subjects('results', 'dataset', name, TypThs)

### Finding Predictions

In [24]:
from scipy import stats
from scipy.spatial.distance import cdist

# cummulative feature selection using Bonferroni corrected threshold 0.01/(Col-1)
def cumulative_features_selection(Pval, PvalPara):
    # Pval: 1-D array of p-values
    FeaInd = np.argsort(Pval)                  # indices sorted by p-value
    SortPval = Pval[FeaInd]                    # sorted p-values

    # Find first index where p-value exceeds threshold
    above_thresh = np.where(SortPval > PvalPara)[0]
    if above_thresh.size > 0:
        ind = above_thresh[0]                  # first index above threshold
    else:
        ind = len(SortPval)                    # all p-values below threshold

    Fea = FeaInd[:ind]                         # keep only significant features
    return Fea

def compute_score(independent_data, typical_data):
    col = independent_data.shape[1]
    
    ind_fea = independent_data[:, :-1]
    typical_data_features = typical_data[:, : -1]
    
    typical_data_labels = typical_data[:, -1]
    typical_group_sz = typical_data_features[typical_data_labels == 1, :]
    typical_group_hc = typical_data_features[typical_data_labels == 2, :]
    
    t_stat, p_val = stats.ttest_ind(typical_group_sz, typical_group_hc, axis=0, equal_var=True)
    
    # print('pvals: ', p_val)
    
    significant_threshold = 0.01 / (col - 1)
    
    selected_features = cumulative_features_selection(p_val, significant_threshold)
    # print('selected features: ', selected_features)
    
    center_sz = np.mean(typical_group_sz[:, selected_features], axis=0).reshape(1, -1)
    center_hc = np.mean(typical_group_hc[:, selected_features], axis=0).reshape(1, -1)
    
    
    # print(center_sz, center_hc)
    
    X = ind_fea[:, selected_features]
    dist1 = cdist(X, center_sz)
    dist2 = cdist(X, center_hc)
    
    distance_typical_group_sz = dist1.mean(axis=1)
    distance_typical_group_hc = dist2.mean(axis=1)
    
    total_distance = distance_typical_group_sz + distance_typical_group_hc
    
    A = distance_typical_group_sz / total_distance
    B = distance_typical_group_hc / total_distance
    
    scores = np.tan((A-B)*np.pi / 2)
    # print('final_scores: ', scores)
    
    return scores
    

def predict_score(subjects: list[str], input_path: str, dataset_path: str, typical_threshold: float):
    
    total_columns = len(subjects)+1
    all_cols = np.arange(total_columns)
    
    for subject_id in range(len(subjects)):
        
        sub_name = subjects[subject_id]
        
        data_file = os.path.join(dataset_path, f'{sub_name}.mat')
        independent_data = load_result_matfile(data_file)[sub_name]
        subject_count, _ = independent_data.shape
        
        ind_sub_labels = independent_data[:, -1]
        total_columns = len(subjects)+1
        independent_score = np.zeros((subject_count, total_columns))
        
        for main_sub_id in range(len(subjects)):
            if main_sub_id == subject_id:
                independent_score[:, subject_id] = ind_sub_labels
                continue
            
            main_sub_name = subjects[main_sub_id]
            main_sub_path = os.path.join(dataset_path, f'{main_sub_name}.mat')
            main_sub_data = load_result_matfile(main_sub_path)[main_sub_name]
            
            input_crf_path = os.path.join(input_path, f'{main_sub_name}_CRF.mat')
            main_sub_crf = load_result_matfile(input_crf_path)['count']
            
            typical_data = main_sub_data[main_sub_crf[:, 3] >= typical_threshold, :]

            independent_score[:, main_sub_id] = compute_score(independent_data, typical_data)
        independent_score[:, -1] = independent_score[:, np.setdiff1d(all_cols, [subject_id, total_columns-1])].mean(axis=1)
        idx = (independent_score[:, :len(subjects)] == 0).any(axis=1)
        independent_score[idx, -1] = 0
        
        output_path = os.path.join(input_path, f'{sub_name}_Score.mat')
        savemat(output_path, {
            sub_name: independent_score
        }, do_compression = True)
    
predict_score(['FBIRN', 'COBRE'], 'results/', 'dataset/', TypThs)

In [25]:
DataName = ["FBIRN", 'COBRE']

def handle_typical_groups(name: str, group: str, data: h5py.Dataset):
    print(f"Dataset: {i}", f"Group: {group}")
    
    # single row, consisting of subject ID's 
    # representing typical subjects after all the iteration 
    print(f"shape: {data.shape} and type: {type(data)}")
    print("Total no.of Typical Subjects: ", data.shape[0])
    print(data)

for i in DataName:
    path= f'results/{i}_Typ.mat'
    data = load_result_matfile(path)
    
    handle_typical_groups(i, "SZ", data['typical_sz'])
    handle_typical_groups(i, "HC", data['typical_hc'])
    
    print('\n\n')

Dataset: FBIRN Group: SZ
shape: (1, 100) and type: <class 'numpy.ndarray'>
Total no.of Typical Subjects:  1
[[  0   1   3   5   7  18  20  23  24  27  39  41  43  44  46  48  51  56
   59  61  62  63  68  69  72  73  77  78  79  80  86  92  93  94  98  99
  101 107 113 119 120 121 125 127 132 138 139 142 147 153 154 159 161 166
  167 169 170 181 185 188 193 194 197 201 202 203 204 205 209 220 224 228
  229 231 233 234 240 241 243 246 250 252 255 259 260 267 272 275 279 281
  283 286 289 290 297 298 299 302 303 305]]
Dataset: FBIRN Group: HC
shape: (1, 95) and type: <class 'numpy.ndarray'>
Total no.of Typical Subjects:  1
[[  6   9  10  11  14  15  19  22  25  26  28  33  36  38  42  45  47  49
   52  55  57  58  71  74  75  81  84  85  87  95  97 100 105 106 110 117
  118 122 123 135 140 141 144 148 150 156 160 162 163 164 171 172 179 183
  187 190 191 206 208 211 212 216 218 219 222 225 232 235 236 237 238 239
  242 244 245 249 257 261 262 263 265 273 274 276 277 280 284 285 287 293
 

In [26]:
import numpy as np

def handle_Indep_Score(name: str, data: h5py.Dataset):
    print(f"======= Independent Score: {name} ========")
    
    # total subjects of current dataset name, then its classification comparing other dataset 
    print(f"Shape: {data.shape} and type: {type(data)}")
    print("top 5 subjects and there score comparing other dataset")
    print(data[:5][:])
    
    total_subjects = data.shape[0]
    avg_column = data[:, -1]
    sz_subjects_count = np.count_nonzero(avg_column >= 0)
    hc_subjects_count = np.count_nonzero(avg_column < 0)
    print("count of subjects having SZ: ", sz_subjects_count)
    print("count of subjects who are healthy: ", hc_subjects_count)
    

DataName = ['FBIRN', 'COBRE']
for i in DataName:
    path = f'results/{i}_Score.mat'
    data = load_result_matfile(path)[i]
    handle_Indep_Score(i, data)
    # print('\n\n')

======= Independent Score: FBIRN ========
Shape: (311, 3) and type: <class 'numpy.ndarray'>
top 5 subjects and there score comparing other dataset
[[ 1.         -0.30615022 -0.30615022]
 [ 1.         -0.48583681 -0.48583681]
 [ 1.         -0.08907705 -0.08907705]
 [ 1.         -0.40001881 -0.40001881]
 [ 2.         -0.43887241 -0.43887241]]
count of subjects having SZ:  164
count of subjects who are healthy:  147
======= Independent Score: COBRE ========
Shape: (157, 3) and type: <class 'numpy.ndarray'>
top 5 subjects and there score comparing other dataset
[[-0.2166395   1.         -0.2166395 ]
 [-0.46306541  1.         -0.46306541]
 [-0.23880238  1.         -0.23880238]
 [ 0.05152334  2.          0.05152334]
 [ 0.55858622  2.          0.55858622]]
count of subjects having SZ:  41
count of subjects who are healthy:  116


In [6]:
import pandas as pd


my_dict = {"a": 1, "b": 2, "c": 3}

df = pd.DataFrame([my_dict.keys()])
print(df)
# print(df['a'])


   0  1  2
0  a  b  c
